In [1]:
import torch

### Creatin a simple vector using torch with random value in it

In [4]:
x=torch.empty(1)
x

tensor([0.])

### Creating a simple vector with random element in it

In [6]:
x=torch.rand(4)
x

tensor([0.7486, 0.1887, 0.4931, 0.9719])

### Creating a matrix with random values

In [9]:
x=torch.rand(4,3)
x              

tensor([[0.7967, 0.9710, 0.4841],
        [0.4180, 0.7882, 0.0882],
        [0.4471, 0.0511, 0.1326],
        [0.0424, 0.2956, 0.9089]])

### Creating a matrix with all entries as ones

In [10]:
x=torch.ones(4,6)
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

### Creating a matrix with all entries as zeros

In [11]:
x=torch.zeros(5,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

## Creating a 3D tensor or matrix

In [13]:
x=torch.ones(2,4,3) #creates a 3d tensor with two 4x3 matrices
x

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

### Creates the two tensors with each tensor containing two 3x4 matrices

In [17]:
x=torch.ones(2,2,3,4)
x

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])

## Operations in torch

### Addition

In [24]:
x=torch.ones(3,3)   #performst the addition element wise like dot product
y=torch.ones(3,3)
print(f"X:\n{x}")
print(f"Y:\n{y}")
print(f"X+Y\n{x+y}")

X:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Y:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
X+Y
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


### Same for sub, multiplication and division

In [29]:
print(f"X-Y:\n{x-y}")
print(f"X*Y:\n{x*y}")
print(f"X/Y:\n{x/y}")
##element wise

X-Y:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
X*Y:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
X/Y:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


### reshape in torch using view #note while reshape number of element must be same

In [38]:
x=torch.rand(3,4)
print(x)
#reshaping to 4x3
x.view(4,3)

tensor([[0.6583, 0.8307, 0.0839, 0.6359],
        [0.3000, 0.8688, 0.9450, 0.4569],
        [0.1346, 0.4586, 0.0711, 0.8444]])


tensor([[0.6583, 0.8307, 0.0839],
        [0.6359, 0.3000, 0.8688],
        [0.9450, 0.4569, 0.1346],
        [0.4586, 0.0711, 0.8444]])

In [40]:
## Reshaping to 1D array
x=torch.rand(5,4)
x.view(20)

tensor([0.1115, 0.8016, 0.4172, 0.5827, 0.4401, 0.3581, 0.2963, 0.0680, 0.1989,
        0.5857, 0.6268, 0.9782, 0.9423, 0.8200, 0.4104, 0.1010, 0.0957, 0.4128,
        0.0459, 0.4338])

In [41]:
## reshping to 2, 10 =20
x.view(-1,10)#means should contain 10 columns rest configure automaticalyy

tensor([[0.1115, 0.8016, 0.4172, 0.5827, 0.4401, 0.3581, 0.2963, 0.0680, 0.1989,
         0.5857],
        [0.6268, 0.9782, 0.9423, 0.8200, 0.4104, 0.1010, 0.0957, 0.4128, 0.0459,
         0.4338]])

### Slicing of an tensor is same as in array

In [45]:
x=torch.rand(5,5)
print(x)
print(x.shape)
y=x[:,:3] #0,1,2
print(y)
print(y.shape)

tensor([[0.1806, 0.4336, 0.0791, 0.1543, 0.6146],
        [0.5537, 0.0711, 0.1157, 0.4637, 0.1101],
        [0.0534, 0.0786, 0.0892, 0.3093, 0.3049],
        [0.4675, 0.5074, 0.7891, 0.0854, 0.0853],
        [0.5172, 0.2334, 0.3987, 0.1059, 0.7020]])
torch.Size([5, 5])
tensor([[0.1806, 0.4336, 0.0791],
        [0.5537, 0.0711, 0.1157],
        [0.0534, 0.0786, 0.0892],
        [0.4675, 0.5074, 0.7891],
        [0.5172, 0.2334, 0.3987]])
torch.Size([5, 3])


### To convert numpy array into tensor and vice-versa

In [46]:
import numpy as np

In [52]:
##numpy to tensor
x=np.array([3,4,5,7,4,22])
print(x)
#to tensor
print("Conversion of Array to Tensor")
y=torch.from_numpy(x)
print(y)

[ 3  4  5  7  4 22]
Conversion of Array to Tensor
tensor([ 3,  4,  5,  7,  4, 22], dtype=torch.int32)


In [55]:
x=torch.rand(5)
print(x)
#conversion to numpy
print("Conversion of Tensor to numpy array")
y=x.numpy()
print(y)

tensor([0.9087, 0.5366, 0.0797, 0.3708, 0.1084])
Conversion of Tensor to numpy array
[0.90874684 0.53657645 0.07965177 0.37079358 0.108401  ]
