## How pytorch forces tensors to shift on gpu

In [11]:
import torch
import numpy as np

In [12]:
x=torch.ones(3,4)

### To check whether cuda is availabe or not

In [13]:
if torch.cuda.is_available():
    device=torch.device('cuda')
else:   #if else portion not mentioned throws an error when printing device bcz cuda not available only cpu
    device=torch.device('cpu')
print(device)
    

cpu


## Pytorch is wll suited to make processing easy for setting of GPU

### To make gpu using tensor for processing 

In [14]:
x=torch.ones(3,device=device)
x #if availabe cude x = tensor([1.,1.,1],device='cuda':0)

tensor([1., 1., 1.])

## if out tensor is on cpu and we want to shift it to gpu use to_device()

In [36]:
x=torch.ones(4,device="cpu")
print(x)

tensor([1., 1., 1., 1.])


In [37]:
#To forcely set x on gpu for processing
x=x.to(device) #using this way we can set to gpu also
x

tensor([1., 1., 1., 1.])

### Creating a matrix of Zeros

In [38]:
ar=torch.zeros(3,4)
## Creating a matix of size 3x4
li=np.arange(12)
ar3=torch.from_numpy(li)
ar3=ar3.view(3,4)

In [39]:
ar3

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int32)

In [40]:
## Creating a matrix of ones 3,4
ar2=torch.ones(3,4)
print(ar2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [41]:
## Addition operation
add=ar3+ar2 #performs the element wise addtion, i.e. vector addition
print(add)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [42]:
##subtraction
sub=ar3-ar2
print(sub)

tensor([[-1.,  0.,  1.,  2.],
        [ 3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10.]])


In [43]:
## multiplication
mul=ar3*ar2 #as ar2 is all 1 we gat ar3 back
print(mul)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [44]:
## div
ar2=ar2*2
print(ar2)
div=ar3/ar2
print(div)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
tensor([[0.0000, 0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000, 3.5000],
        [4.0000, 4.5000, 5.0000, 5.5000]])


## To Check whether CPU is available or GPU is available

**if Cuda means notebook is transferred on GPU**

In [53]:
### Check whether GPU is available or not
if torch.cuda.is_available():
    device=torch.device('cuda')
else:
    device=torch.device('cpu')

In [54]:
print(device)

cpu


### To shift the particular tensor on the GPU

In [56]:
y=torch.ones(3,4,device=device) #here we have cpu if cuda available then shifts to GPU
print(y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### Another way to shift the already created tensor to GPU

In [61]:
x=torch.zeros(3,4)
#already created
x=x.to(device)  #if cuda shifts to cude otherwise cpu
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


## Arguments

**Requires Grad**