**A DataLoader in PyTorch is an iterable object that loads data from a dataset in batches. It is a useful tool for training deep learning models, as it can help to improve the efficiency and performance of the training process.
The DataLoader class takes in a dataset object and a number of configuration options, such as the batch size, the number of workers, and the shuffle flag. It then loads the data from the dataset in batches and returns it in a format that can be consumed by the model.
The DataLoader class can be used to load data from a variety of sources, including files, databases, and memory. It can also be used to load data in parallel, which can improve the performance of the training process.**

In [15]:
import torch
from torch.utils.data import Dataset,DataLoader
import numpy as np

### This class will return the dataset obeject which has 3 modules

In [16]:
# This set is given as input to the Datasets class
class OurDataset(Dataset):
    def __init__(self,x,y):
        #data loadeing
        self.x=torch.from_numpy(x) #conversion of numpy to tensor
        self.y=torch.from_numpy(y)
    def __getitem__(self,index):
        #dataset[0]
        return self.x[index],self.y[index]
    def __len__(self):
        #lengths
        return len(self.x)

In [17]:
## Creating random dependent variable vecotor and input features
x=np.random.randn(150,5)
y=np.random.randn(150,1)

In [18]:
x[:20,:]

array([[ 6.13762630e-01, -1.62167666e+00,  6.76988233e-01,
         9.88588567e-01, -2.55830592e+00],
       [-2.32718578e+00,  1.20334099e+00, -6.56168689e-03,
         1.36664948e+00, -5.04902531e-01],
       [-7.75947238e-02,  2.40125951e+00, -7.32267189e-01,
         1.68814996e+00,  3.38689610e+00],
       [-1.29730677e-01,  2.44378165e-01, -1.41977807e-01,
         4.07358824e-01, -2.62095957e-01],
       [-1.34597552e+00,  7.69223445e-01, -6.30866156e-01,
         5.68207912e-01,  7.80961405e-01],
       [ 1.14777941e+00,  2.42660117e-01, -1.19416763e+00,
         1.30905940e+00, -7.03807918e-01],
       [-1.07524166e-01,  6.96887903e-01, -1.69362673e-01,
         2.47982379e+00, -1.29242058e+00],
       [ 1.52769170e+00,  1.50078275e-01, -1.90229558e-01,
        -1.05958466e+00, -9.82781316e-01],
       [-5.11955164e-01, -7.25580672e-01,  5.47984492e-01,
        -1.28096374e-01,  1.89203756e+00],
       [-6.89703818e-01, -5.69183966e-01,  1.98903086e+00,
         7.80283499e-01

### Creates a batch of size=5, and verifying

In [19]:
#creating an object of dataset class, which is required to dataloader
dataset=OurDataset(x,y)
dataloader=DataLoader(dataset=dataset,batch_size=5,shuffle=False)
#Creating the iterator of the dataloader object
dataiter=iter(dataloader)
for i,(inputs,labels) in enumerate(dataloader):
    print(inputs)
    print(labels)
    break

tensor([[ 0.6138, -1.6217,  0.6770,  0.9886, -2.5583],
        [-2.3272,  1.2033, -0.0066,  1.3666, -0.5049],
        [-0.0776,  2.4013, -0.7323,  1.6881,  3.3869],
        [-0.1297,  0.2444, -0.1420,  0.4074, -0.2621],
        [-1.3460,  0.7692, -0.6309,  0.5682,  0.7810]], dtype=torch.float64)
tensor([[-0.4294],
        [-0.2300],
        [ 0.6812],
        [ 0.2458],
        [-0.8515]], dtype=torch.float64)


### iterator always given next 5 batch whenever we run it

In [20]:
next(dataiter)

[tensor([[ 0.6138, -1.6217,  0.6770,  0.9886, -2.5583],
         [-2.3272,  1.2033, -0.0066,  1.3666, -0.5049],
         [-0.0776,  2.4013, -0.7323,  1.6881,  3.3869],
         [-0.1297,  0.2444, -0.1420,  0.4074, -0.2621],
         [-1.3460,  0.7692, -0.6309,  0.5682,  0.7810]], dtype=torch.float64),
 tensor([[-0.4294],
         [-0.2300],
         [ 0.6812],
         [ 0.2458],
         [-0.8515]], dtype=torch.float64)]